spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    show-sql: true
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        # none
    #database-platform: org.hibernate.dialect.H2Dialect
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: f7a9fc97c6ad206d16f1452ec5174805
#            client-secret: YWxsNR9PN1Cd8Rsv3u5of2ja62GC1OxF
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
